name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/aottr/patreon-sync:latest

    - name: Publish Docker image to Github Packages
      shell: bash
      env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        echo $CR_TOKEN | docker login ghcr.io --username alexottr --password-stdin
        docker push ghcr.io/aottr/patreon-sync:latest
        docker logout
